### ISSUE TITLE
TensorRT-LLM 跑 自己的 72B  GPTQ 量化模型

### ISSUE THREAD

**Issue by CallmeZhangChenchen** [QwenLM/Qwen2#712] opened 2024-06-27 09:54 UTC
打扰了  
Qwen/Qwen2-72B-Instruct-GPTQ-Int4  这个模型直接可以用 TensorRT-LLM 跑通，效果不错

但是自己训练的 Qwen2-72B，然后根据教程 GPTQ  4bit量化，https://qwen.readthedocs.io/en/latest/quantization/gptq.html 
最后用 TensorRT-LLM，会出错 

比较了一下区别，Qwen/Qwen2-72B-Instruct-GPTQ-Int4/config.json中  "max_window_layers": 70  
但是自己 GPTQ 量化后的config.json "max_window_layers": 80 ，与Qwen/Qwen2-72B-Instruct/config.json相同

重新改下，依旧会报  维度对不齐的问题

![image](https://github.com/QwenLM/Qwen2/assets/57712520/26837ad6-bd0e-45f1-9f0c-f4c87109748f)

想问下，我有哪步 走错了吗？Qwen/Qwen2-72B-Instruct-GPTQ-Int4 这个模型有做过什么更改吗

**Comment by jklj077** [comment] 2024-06-27 10:17
Closed as duplicate of https://github.com/QwenLM/Qwen2/issues/578 .

**Closed by jklj077** 2024-06-27 10:17 UTC
Labels: duplicate

**Comment by tianzuishiwo** [comment] 2024-08-26 07:41
Qwen/Qwen2-72B-Instruct-GPTQ-Int4 转换tensorRT engines成功，但是推理结果是坏的，什么情况知道吗？

[TensorRT-LLM][INFO] [MemUsageChange] Allocated 30.45 GiB for max tokens in paged KV cache (99776).
[08/26/2024-14:34:24] [TRT-LLM] [I] Load engine takes: 26.76789355278015 sec
Input [Text 0]: "<|im_start|>system
You are a helpful assistant.<|im_end|>
<|im_start|>user
Hello, what's your name?<|im_end|>
<|im_start|>assistant
"
Output [Text 0 Beam 0]: "颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠颠"
[TensorRT-LLM][INFO] Refreshed the MPI local session

**Comment by jklj077** [comment] 2024-08-29 08:34
@tianzuishiwo different issue, open a new one.
