### ISSUE TITLE
希望增加qwen2-14B

### ISSUE THREAD

**Issue by lufred8341** [QwenLM/Qwen2#702] opened 2024-06-24 13:34 UTC
希望增加qwen2-14B大小的模型，这个大小对于我正好。谢谢千问团队。

**Comment by makeximu** [comment] 2024-06-25 01:27
同

**Comment by jklj077** [comment] 2024-06-25 02:38
closed as duplicate of https://github.com/QwenLM/Qwen2/issues/482

**Closed by jklj077** 2024-06-25 02:38 UTC
Labels: duplicate
